### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by valkone** [mar0der/LOSANGELES#2]
- [x] when you shoot empty box should says: "Illegal move: cannot pop missing ballon!"
- [x] when you have high score should says: "Congratulations! You popped all baloons in 11 moves."
- [x] when you finish the game, it should start the game automatically
- [x] when you type the exit command, it should says: "Good bye"

**Comment by IvanHristov** [comment]
Problem solved
